version: "3.8"

services:
  postgres:
    image: postgres:16.4
    container_name: shorty_db
    restart: always
    environment:
      POSTGRES_USER: shorty_user
      POSTGRES_PASSWORD: shorty_password
      POSTGRES_DB: shortydb
    ports:
      - "5432:5432"
    volumes:
      - shorty_db_data:/var/lib/postgresql/data

volumes:
  shorty_db_data:
